# Generated by Django 6.1.1 on 2026-09-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours', models.FloatField()),
                ('attendance', models.FloatField()),
                ('previous_marks', models.FloatField()),
                ('assignments', models.FloatField()),
                ('predicted_performance', models.FloatField()),
                ('risk_level', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
